CREATE TYPE "order_status" AS ENUM (
	'queue',
	'finished',
	'way',
	'canceled',
	'preparing'
);

CREATE TABLE IF NOT EXISTS "products" (
	"id" UUID NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	"description" TEXT,
	"price" INTEGER NOT NULL,
	"image_path" TEXT,
	"is_avaliable" BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "users" (
	"id" UUID NOT NULL UNIQUE,
	"name" TEXT,
	"email" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	"address" TEXT,
	"is_admin" BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "orders" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID NOT NULL,
	"total_price" INTEGER NOT NULL,
	"date" TIMESTAMP NOT NULL,
	"status" ORDER_STATUS NOT NULL DEFAULT queue,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "order_products" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"order_id" UUID NOT NULL,
	"product_id" UUID NOT NULL,
	"product_quantity" INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY("id")
);



ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "orders"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "products"
ADD FOREIGN KEY("id") REFERENCES "order_products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "orders"
ADD FOREIGN KEY("id") REFERENCES "order_products"("order_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;